spring.application.name=bootSpring
spring.datasource.url=jdbc:postgresql://9854.me:5432/training
spring.datasource.username=gaurav
spring.datasource.password=gauravbhatt
spring.datasource.driver-class-name=org.postgresql.Driver
debug=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update