package com.gal.model;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;

//Capgemini 
//hibernate_training 
//trainee : id supersetid autogenerated 
//batches 
//trainer 
//content : java, python, dotnet 
//venue galgotia university , 
//attendance/exam date marks 

@Entity
public class Project {
	@SequenceGenerator(name = "projectidseq", allocationSize = 1, initialValue = 1001, sequenceName = "projectidseq")

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "projectidseq")
	int projectid;

	@Column(name = "startDate")
	Date startDate;
	@Column(name = "endDate")
	Date endDate;
	String client;
	Double budget;

	@OneToOne
	@JoinColumn(name = "mangerid")
	Employee manager;

	@ManyToMany
	@JoinTable(name = "project_employee", joinColumns = { @JoinColumn(name = "projectid") }, inverseJoinColumns = {
			@JoinColumn(name = "employeeid") })
	List<Employee> employees = new ArrayList<>();
	// by default : table : project_employee , foreign keys : projectid employee_id

	public Project(Date startDate, Date endDate, String client, Double budget) {
		super();
		this.startDate = startDate;
		this.endDate = endDate;
		this.client = client;
		this.budget = budget;
	}

	public List<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}

	public String getClient() {
		return client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public Employee getManager() {
		return manager;
	}

	public void setManager(Employee manager) {
		this.manager = manager;
	}

	public Project() {
		super();
	}

	public int getProjectid() {
		return projectid;
	}

	public void setProjectid(int projectid) {
		this.projectid = projectid;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Double getBudget() {
		return budget;
	}

	public void setBudget(Double budget) {
		this.budget = budget;
	}

	@Override
	public String toString() {
		return "Project [startDate=" + startDate + ", endDate=" + endDate + ", client=" + client + ", budget=" + budget
				+ ", manager=" + manager + "]";
	}

}
